parameters:
  environment: ''

stages:
  - stage: Analyze
    displayName: Analyzing
    dependsOn: []
    jobs:
      - job: CredScan
        displayName: Scan for credentials
        steps:
          - task: CredScan@3

      - job: ComponentGovernanceDetection
        displayName: Component governance detection
        steps:
          - task: ComponentGovernanceComponentDetection@0
            inputs:
              scanType: Register
              verbosity: Verbose
              alertWarningLevel: High

      - job: PublishSecurityAnalysisLogs
        displayName: Publish security analysis logs
        dependsOn:
          - CredScan
          - ComponentGovernanceDetection
        steps:
          - task: PublishSecurityAnalysisLogs@3
            inputs:
              ArtifactName: CodeAnalysisLogs
              ArtifactType: Container
              AllTools: true
              ToolLogsNotFoundAction: Standard
